server.port=8082
spring.application.name=order-service

# Active profile
spring.profiles.active=dev

# Actuator
management.endpoints.web.base-path=/api/orders/actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Logging
logging.level.com.example=INFO
logging.file.name=logs/order-service.log